### ISSUE TITLE
POST /addUser의 응답이 오지 않을 케이스가 존재합니다.

### ISSUE THREAD

**Issue by potados99** [WBPBP/preshoes-server#2]
안녕하세요.

회원가입 부분부터 코드를 정독하다가 위험해 보이는 부분을 발견하여 이슈 남깁니다. 아래는 해당 라우터 코드 전문입니다.

~~~js
router.post('/addUser',function(req,res,next){
   var user = req.body.user_name;
   var key = 0; //중복여부 키 
   //회원가입에 들어갈 정보들 
   const user_name = req.body.user_name;
	const user_pwd = req.body.user_pwd;
	const user_gender = req.body.user_gender;
	const user_age = req.body.user_age;
	const user_weight = req.body.user_weight;
	const user_height = req.body.user_height;
	const user_wpattern = req.body.user_wpattern;
	const query = `insert into user(user_name, user_pwd,user_gender,user_age,user_weight,user_height,user_wpattern) values ('${user_name}', '${user_pwd}','${user_gender}','${user_age}','${user_weight}','${user_height}','${user_wpattern}')`;
     db.serialize();
   db.all('SELECT * FROM user WHERE user_name = ?',user,function(err,db_data){ //그 아이디가 있는지 확인 
      db_result = db_data
	  if(validator.isEmail(user)){
		  if(db_result.length==0){
		  key=1;}
		  else{
			  console.log('sorry, that ID is already existed');
			  key=0;
		  }
	  }
	  else{
		  console.log('wrong form of email');
		  key=-1;
	  }
		  
	  if( key == 1) //중복이 아니므로
      {
       db.run(query,function(err,db_data){ //인서트 하고 성공했다는 메세지 보내준다. 
             console.log('insert user table :',user_name);
             res.send('key'); 
         });
      }
      else //아님 페일 
      {
         console.log('sign up failure'); 
         res.send('key');
      }
   });

});
~~~

코드의 흐름을 보겠습니다.

## 정상 흐름

1. DB가 정상적으로 초기화됩니다.
2. 요청으로부터(아마 `form-urlencoded`)  body를 추출합니다.
3. 추출한 데이터 중 사용자의 이메일 주소가 중복되는지 확인합니다.
4. 중복되지 않는다면 `user` 테이블에 새로운 row를 추가합니다.

### DB가 초기화되지 않는 경우

DB 초기화에 실패하면 `db` 객체에는 `null` 또는 `undefined`가 대입될 것입니다. 어떠한 경우든, `db.serialize();` 호출은 예외를 일으킬 것입니다. 만약 처리되지 않은 예외가 발생하면 서버는 자동으로 응답 코드 500을 돌려줄 것입니다(추측).

### 사용자가 보낸 데이터가 불완전한 경우

`req.body.user_name`이 `undefined`일 수 있습니다. 개발자의 실수일 수도 있고, 사용자의 악의적 행동일 수도 있습니다. 이 경우 DB에 아무런 검증 없이 잘못된 값이 들어갑니다. 해당 column이 nonnull 속성을 지닌다면 예외로 이어질 것입니다.

### 쿼리에 실패했을 경우

`db.all`로 시작하는 쿼리 호출에 실패하였을 경우, 콜백의 인자로 들어오는 `db_data`는 `null` 또는 `undefined`일 수 있습니다. 이 상태에서 `db_result.length` 속성에 접근하면 예외가 발생할 것입니다.

**Comment by hseol** [comment]
아 저 serialize() 안해도 될겁니다.. ㅎㅎ 안해도 돌아가긴 하는데 뭐 테스트 해보려고 넣어놨던 코드 같네요 
user.name 이 notnull 이긴 한데 아직 불완전한 경우는 안해봐서 모르겠군요 name 이 이메일 형식의 주소로 해놓긴 한건데..

**Comment by potados99** [comment]
답변 감사합니다.

1. `NOT NULL` 속성이 붙은 컬럼에 `null` 또는 `undefined`를 삽입하면 문제가 생깁니다.

2. 사용자가 보내는 데이터가 항상 유효할 것이라는 보장이 절대 없습니다. 실수로, 또는 악의적으로 클라이언트가 필드를 빼먹고 보내거나 유해한 데이터를 보낼 수 있습니다.

3. 개발자도 실수를 합니다. 예를 들어, Express에서 body parser 미들웨어 선언을 빼먹으면 사용자의 이메일 주소가 들어있을 것이라고 기대되는 `req.body.user`에는 아무 것도 들어있지 않을 것입니다.

4. 따라서 `사용자가 보낸  데이터를 담고 있다고 생각되는 변수`를 그대로 데이터베이스에 집어넣으면, 높은 확률로 예외가 발생합니다. 추후에 서버가 이유 없이 죽는 일이 자주 발생하게 될 수도 있습니다.

5. **코드는 거의 항상 예상과 다르게 움직입니다.** 따라서 발생할 수 있는 모든 경우를 연구하고 이에 대응해야 합니다.

읽어주셔서 감사합니다.

**Comment by hseol** [comment]
감사합니다. 궁금한게 있습니다. 
실제로 사용자가 쓸 때는 앱에서? 선택을 하는데 만약 그 사람이 넘어가거나 안 쓰고 저장을 하면 넘어가지 않게 하려는건 서버쪽에서 구현하는건가요?

**Comment by potados99** [comment]
양쪽 모두에서 해야 합니다.

클라이언트에서 모든 form을 입력하도록 UI로 강제해야 합니다.

서버에서는 사용자가 넘긴 데이터를 믿지 말아야 합니다. 클라이언트에서 검증이 끝났을 지라도, 사용자의 데이터는 항상 손상되어 있거나 유해하다고 간주해야 합니다.

따라서 서버 측에서도 검증 절차를 두어야 합니다.

마지막으로, [이 글](http://labs.brandi.co.kr//2018/03/02/kimwk.html) 꼭 참고해주시면 감사하겠습니다. 올해 초에 읽고 많은 도움 받은 글이라 추천드리고 싶습니다.
