### ISSUE TITLE
SQL injection 취약점 발견

### ISSUE THREAD

**Issue by potados99** [WBPBP/preshoes-server#3]
`routes/join.js` 31번 줄입니다.

~~~js
const query = `insert into user(user_name, user_pwd,user_gender,user_age,user_weight,user_height,user_wpattern) values ('${user_name}', '${user_pwd}','${user_gender}','${user_age}','${user_weight}','${user_height}','${user_wpattern}')`;
~~~

사용자의 입력이 escape 없이 쿼리문에 직접 사용되었습니다. 이러한 형태의 쿼리문은 SQL 삽입 공격에 매우 취약합니다.

예를 들어, 사용자가 나이를 `', '`와 같이 대입하면 컬럼 갯수 불일치로 에러가 발생할 수 있습니다.

만약 DB가 다중 쿼리를 허용한다면, 사용자가 `user_wpattern`을 `'); drop table user; --`와 같이 꾸며 아래와 같은 쿼리가 실행되도록 유도할 수도 있습니다.
~~~js
const query = `insert into user(user_name, user_pwd,user_gender,user_age,user_weight,user_height,user_wpattern) values ('${user_name}', '${user_pwd}','${user_gender}','${user_age}','${user_weight}','${user_height}',''); drop table user; --')`;
~~~

**Comment by hseol** [comment]
엄.. 뒤에거는 이해하지 못했는데, 걸음걸이 패턴을 빼고 다른 항목들은 다 not null입니다 회원가입할때 애초에 꼭 선택해야하는 것들이라서요... 걸을걸이 패턴에는 ''이렇게 비워놔도 무방합니다.
